# DataSource
spring:
  datasource:
    url: jdbc:mysql://www.joonsoo.net:13306/dev_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: SearchDev
    password: lotte1234!
    driver-class-name: com.mysql.jdbc.Driver

server:
  port:
    10180

flex:
  class:
    path: /Users/jb/git/flex-api/
    name: Solution
    extension: .java
  method:
    name: solution
