spring:
  datasource:
    url: jdbc:mysql://www.joonsoo.net:13306/search_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: dev
    password: searchdev
    driver-class-name: com.mysql.jdbc.Driver
  config:
    activate:
      on-profile: prod-blue

server:
  port:
    10101

management:
  endpoints:
    web:
      base-path: /health
      path-mapping:
        health : healthcheck
  endpoint:
    health:
      show-details: never

flex:
  class:
    path: /Users/jb/git/flex-api/
    name: Solution
    extension: .java
  method:
    name: solution

---

spring:
  datasource:
    url: jdbc:mysql://www.joonsoo.net:13306/search_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: dev
    password: searchdev
    driver-class-name: com.mysql.jdbc.Driver
  config:
    activate:
      on-profile: prod-green

management:
  endpoints:
    web:
      base-path: /health
      path-mapping:
        health : healthcheck
  endpoint:
    health:
      show-details: never

server:
  port:
    10102

flex:
  class:
    path: /Users/jb/git/flex-api/
    name: Solution
    extension: .java
  method:
    name: solution

---
# DataSource
spring:
  config:
    activate:
      on-profile: stg
  datasource:
    url: jdbc:mysql://www.joonsoo.net:13306/dev_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: SearchDev
    password: lotte1234!
    driver-class-name: com.mysql.jdbc.Driver

server:
  port:
    10180

management:
  endpoints:
    web:
      base-path: /health
      path-mapping:
        health : healthcheck
  endpoint:
    health:
      show-details: always

flex:
  class:
    path: /Users/jb/git/flex-api/
    name: Solution
    extension: .java
  method:
    name: solution

---

# DataSource
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://www.joonsoo.net:13306/dev_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: SearchDev
    password: lotte1234!
    driver-class-name: com.mysql.jdbc.Driver

server:
  port:
    10180

management:
  endpoints:
    web:
      base-path: /health
      path-mapping:
        health : healthcheck
  endpoint:
    health:
      show-details: always

flex:
  class:
    path: /Users/jb/git/flex-api/
    name: Solution
    extension: .java
  method:
    name: solution