spring:
  datasource:
    url: jdbc:mysql://www.joonsoo.net:13306/search_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: dev
    password: searchdev
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: prod-blue

server:
  port:
    10101

logging:
  file:
    name: /Users/dev/app/flexAPI/log/server.log
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd
    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p}
      ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    level: '%5p'
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

management:
  endpoints:
    web:
      base-path: /flex
      path-mapping:
        health : healthcheck
  endpoint:
    health:
      show-details: never

flex:
  class:
    path: /Users/dev/app/flexAPI/data/
    name: Solution
    extension: .java
  method:
    name: solution

---

spring:
  datasource:
    url: jdbc:mysql://www.joonsoo.net:13306/search_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: dev
    password: searchdev
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: prod-green

management:
  endpoints:
    web:
      base-path: /flex
      path-mapping:
        health : healthcheck
  endpoint:
    health:
      show-details: never

server:
  port:
    10102

logging:
  file:
    name: /Users/dev/app/flexAPI/log/server.log
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd
    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p}
      ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    level: '%5p'
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

flex:
  class:
    path: /Users/dev/app/flexAPI/data/
    name: Solution
    extension: .java
  method:
    name: solution

---
# DataSource
spring:
  config:
    activate:
      on-profile: stg
  datasource:
    url: jdbc:mysql://www.joonsoo.net:13306/dev_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: SearchDev
    password: lotte1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port:
    10180

management:
  endpoints:
    web:
      base-path: /flex
      path-mapping:
        health : healthcheck
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: /Users/dev/app/flexAPI/log/server.log
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd
    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p}
      ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    level: '%5p'
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

flex:
  class:
    path: /Users/jb/git/flex-api/
    name: Solution
    extension: .java
  method:
    name: solution

---

# DataSource
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://www.joonsoo.net:13306/search_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: dev
    password: searchdev
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port:
    10180

management:
  endpoints:
    web:
      base-path: /flex
      path-mapping:
        health : healthcheck
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: /Users/dev/app/flexAPI/log/server.log
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd
    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p}
      ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    level: '%5p'
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

flex:
  class:
    path: /Users/jb/git/flex-api/
    name: Solution
    extension: .java
  method:
    name: solution